// <auto-generated />
namespace Freelance.Provider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_setting_imageName_to_profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_setting_imageName_to_profile));
        
        string IMigrationMetadata.Id
        {
            get { return "201705080942132_added_setting_imageName_to_profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
